name: Build Unsigned iOS IPA

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'  # Use the latest stable version or specify an exact version if needed
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Install xcodeproj gem
        run: gem install xcodeproj

      - name: Add Release build configuration if missing
        run: |
          cd ios
          ruby -e "
          require 'xcodeproj'
          project = Xcodeproj::Project.open('Runner.xcodeproj')
          if project.build_configuration_list['Release'].nil?
            profile = project.build_configuration_list['Profile']
            if profile
              release = profile.duplicate
              release.name = 'Release'
              project.build_configuration_list.build_configurations << release
              project.targets.each do |target|
                if target.build_configuration_list['Release'].nil?
                  target.build_configuration_list.build_configurations << release
                end
              end
            end
          end
          project.save
          "

      - name: Build iOS app (unsigned)
        run: flutter build ios --release --no-codesign

      - name: Create unsigned IPA
        run: |
          cd build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload/
          zip -r unsigned.ipa Payload/

      - name: Upload unsigned IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-ipa
          path: build/ios/iphoneos/unsigned.ipa
          retention-days: 7  # Adjust retention as needed
