name: Build iOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    env:
      KEYCHAIN_PATH: build.keychain-db
      KEYCHAIN_PASSWORD: Pre$ton01

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze Dart code
        run: flutter analyze

      #- name: Run tests
      # run: flutter test

      - name: Set up keychain
        run: |
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security default-keychain -s $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

      - name: Download certificate
        run: echo "${{ secrets.IOS_CERTIFICATE_APPSTORE }}" | base64 --decode > /tmp/apple_cert.p12

      - name: Check decoded certificate file
        run: |
          ls -l /tmp/apple_cert.p12
          file /tmp/apple_cert.p12 || echo "File type check failed - may not be a valid PKCS12 file"

      - name: Debug print P12_PASSWORD
        run: echo "Using P12_PASSWORD: ${{ secrets.P12_PASSWORD }} (should be Not$erp01, masked as *** if correct)"

      - name: Import certificate
        run: security import /tmp/apple_cert.p12 -P "${{ secrets.P12_PASSWORD }}" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
        continue-on-error: false  # Fail if import fails

      - name: Download provisioning profile
        run: echo "${{ secrets.PROVISIONING_PROFILE_APPSTORE }}" | base64 --decode > /tmp/app.mobileprovision

      - name: Check decoded provisioning profile
        run: |
          ls -l /tmp/app.mobileprovision
          file /tmp/app.mobileprovision || echo "File type check failed - may not be a valid mobileprovision file"

      - name: Extract provisioning profile details
        run: |
          security cms -D -i /tmp/app.mobileprovision > /tmp/decoded.plist
          PROFILE_UUID=$(/usr/libexec/PlistBuddy -c "Print :UUID" /tmp/decoded.plist || echo "UUID extraction failed")
          TEAM_ID=$(/usr/libexec/PlistBuddy -c "Print :TeamID" /tmp/decoded.plist || echo "TeamID extraction failed")
          PROFILE_SPECIFIER=$(/usr/libexec/PlistBuddy -c "Print :Name" /tmp/decoded.plist || echo "Name extraction failed")
          echo "PROFILE_UUID=$PROFILE_UUID" >> $GITHUB_ENV
          echo "TEAM_ID=$TEAM_ID" >> $GITHUB_ENV
          echo "PROFILE_SPECIFIER=$PROFILE_SPECIFIER" >> $GITHUB_ENV
          echo "Extracted PROFILE_UUID: $PROFILE_UUID"
          echo "Extracted TEAM_ID: $TEAM_ID"
          echo "Extracted PROFILE_SPECIFIER: $PROFILE_SPECIFIER"

      - name: Install provisioning profile
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp /tmp/app.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/${{ env.PROFILE_UUID }}.mobileprovision

      - name: Extract bundle ID
        run: |
          BUNDLE_ID=$(/usr/libexec/PlistBuddy -c "Print :CFBundleIdentifier" ios/Runner/Info.plist)
          echo "BUNDLE_ID=$BUNDLE_ID" >> $GITHUB_ENV
          echo "Extracted BUNDLE_ID: $BUNDLE_ID"

      - name: Update Xcode project for manual signing
        run: |
          PROJECT_PATH="ios/Runner.xcodeproj/project.pbxproj"
          sed -i '' 's/CODE_SIGN_STYLE = Automatic;/CODE_SIGN_STYLE = Manual;/g' $PROJECT_PATH
          sed -i '' 's/DEVELOPMENT_TEAM = "";/DEVELOPMENT_TEAM = "${{ env.TEAM_ID }}";/g' $PROJECT_PATH
          sed -i '' 's/PROVISIONING_PROFILE_SPECIFIER = "";/PROVISIONING_PROFILE_SPECIFIER = "${{ env.PROFILE_SPECIFIER }}";/g' $PROJECT_PATH
          sed -i '' 's/CODE_SIGN_IDENTITY = "";/CODE_SIGN_IDENTITY = "Apple Distribution";/g' $PROJECT_PATH
          sed -i '' 's/CODE_SIGN_IDENTITY\[sdk=iphoneos\*\] = "";/CODE_SIGN_IDENTITY\[sdk=iphoneos\*\] = "Apple Distribution";/g' $PROJECT_PATH

      - name: Create export options plist
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>' > exportOptions.plist
          echo '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">' >> exportOptions.plist
          echo '<plist version="1.0">' >> exportOptions.plist
          echo '<dict>' >> exportOptions.plist
          echo '  <key>compileBitcode</key>' >> exportOptions.plist
          echo '  <false/>' >> exportOptions.plist
          echo '  <key>method</key>' >> exportOptions.plist
          echo '  <string>app-store</string>' >> exportOptions.plist
          echo '  <key>teamID</key>' >> exportOptions.plist
          echo "  <string>${{ env.TEAM_ID }}</string>" >> exportOptions.plist
          echo '  <key>provisioningProfiles</key>' >> exportOptions.plist
          echo '  <dict>' >> exportOptions.plist
          echo "    <key>${{ env.BUNDLE_ID }}</key>" >> exportOptions.plist
          echo "    <string>${{ env.PROFILE_SPECIFIER }}</string>" >> exportOptions.plist
          echo '  </dict>' >> exportOptions.plist
          echo '</dict>' >> exportOptions.plist
          echo '</plist>' >> exportOptions.plist
          cat exportOptions.plist  # Print for debugging

      - name: Build IPA
        run: flutter build ipa --release --export-options-plist=exportOptions.plist

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-app
          path: build/ios/ipa/*.ipa
          retention-days: 5  # Adjust as needed
