name: Build Unsigned iOS IPA

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x' # Latest stable version
          channel: 'stable'
          cache: true

      # Check for outdated packages
      - name: Check for outdated packages
        run: flutter pub outdated

      # Install dependencies
      - name: Install dependencies
        run: |
          flutter pub get
          cd ios
          pod install

      # Fix Xcode project configurations
      - name: Fix Xcode project configurations
        run: |
          gem install xcodeproj
          cd ios
          ruby fix_xcodeproj.rb

      # Build unsigned iOS app and package into unsigned IPA
      - name: Build unsigned IPA
        run: |
          flutter build ios --release --no-codesign
          cd ios
          xcodebuild -workspace Runner.xcworkspace -scheme Runner -sdk iphoneos17.5 -configuration Release archive -archivePath ../build/Runner.xcarchive CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
          xcrun xcodebuild -exportArchive -archivePath ../build/Runner.xcarchive -exportOptionsPlist exportOptions.plist -exportPath ../build
          ls -l ../build/unsigned.ipa
        env:
          DEVELOPER_DIR: /Applications/Xcode_16.0.app/Contents/Developer # Specify Xcode version if needed

      # Upload the IPA as an artifact
      - name: Upload unsigned IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-ipa
          path: build/unsigned.ipa
          retention-days: 7
