name: Build Signed iOS IPA

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-13

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.7'
          channel: 'stable'
          cache: true

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Decode and import certificate
      - name: Import Certificate
        run: |
          echo "${{ secrets.IOS_CERTIFICATE_APPSTORE }}" | base64 --decode > certificate.p12
          ls -l certificate.p12  # Debug: Check file size
          security create-keychain -p pwd ~/Library/Keychains/app-signing.keychain-db
          security default-keychain -s ~/Library/Keychains/app-signing.keychain-db
          security unlock-keychain -p pwd ~/Library/Keychains/app-signing.keychain-db
          security import certificate.p12 -k ~/Library/Keychains/app-signing.keychain-db -P "${{ secrets.P12_PASSWORD }}" -T /usr/bin/codesign || echo "Import failed, check password"
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k pwd ~/Library/Keychains/app-signing.keychain-db
          
      # Decode and install provisioning profile
      - name: Install Provisioning Profile
        run: |
          echo "${{ secrets.PROVISIONING_PROFILE_APPSTORE }}" | base64 --decode > profile.mobileprovision
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/"${{ secrets.PROFILE_NAME }}".mobileprovision

      # Build signed IPA
      - name: Build signed IPA
        run: flutter build ipa --release --export-options-plist=ios/ExportOptions.plist

      # Upload the IPA as an artifact
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: app-ipa
          path: build/ios/ipa/*.ipa

      # Cleanup (always run)
      - name: Cleanup
        if: always()
        run: |
          security delete-keychain ~/Library/Keychains/app-signing.keychain-db || true
          rm -f certificate.p12 profile.mobileprovision
