name: Build Unsigned iOS IPA

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Flutter environment
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Install CocoaPods dependencies (for iOS plugins)
      - name: Install CocoaPods
        run: |
          cd ios
          pod install --repo-update
          cd ..

      # Build unsigned IPA
      - name: Build unsigned IPA
        run: flutter build ipa --release --no-codesign --export-options-plist=ios/exportOptions.plist

      # Upload the IPA as an artifact
      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-ipa
          path: build/ios/ipa/*.ipa
