name: Build Unsigned iOS IPA

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.7'  # Use the latest stable version or specify a exact version if needed
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS app (unsigned)
        run: flutter build ios --release --no-codesign

      - name: Create unsigned IPA
        run: |
          cd build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload/
          zip -r unsigned.ipa Payload/

      - name: Upload unsigned IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-ipa
          path: build/ios/iphoneos/unsigned.ipa
          retention-days: 7  # Adjust retention as needed
