name: Build iOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-14  # Specifies the macOS runner version for iOS builds.
    timeout-minutes: 45  # Prevents infinite hangs, fails job after 45 minutes.

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Checks out the repository code to the runner.

      - name: Set up Flutter
        uses: subosito/flutter-action@v2  # Installs Flutter on the runner.
        with:
          channel: 'stable'  # Uses the stable channel for reliability.

      - name: Install dependencies
        run: flutter pub get  # Fetches Flutter dependencies.

      - name: Clean Flutter build
        run: |
          flutter clean
          flutter pub get

      - name: Install CocoaPods
        run: cd ios && pod install --repo-update && cd ..

      - name: Analyze Dart code
        run: flutter analyze  # Runs static analysis on the Dart code to catch issues early.

      - name: Build Unsigned IPA
        run: flutter build ipa --release --no-codesign -v  # Builds unsigned IPA.

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4  # Uploads the built IPA as an artifact.
        with:
          name: ios-app  # Artifact name.
          path: build/ios/ipa/*.ipa  # Path to IPA.
          retention-days: 5  # Keeps for 5 days.
