Skip to content
Navigation Menu
markoviandevelopments
brubaker_home_app

Type / to search
Code
Issues
Pull requests
Actions
Projects
Security
Insights
Settings
Build iOS IPA
Update Podfile #161
Jobs
Run details
Workflow file for this run
.github/workflows/build_ios.yml at 122c37e
name: Build iOS IPA
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-ios:
    runs-on: macos-13
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.2'
          channel: 'stable'
          cache: true
      # Install dependencies
      - name: Install dependencies
        run: flutter pub get
      # Build unsigned iOS app and package into unsigned IPA
      - name: Build unsigned IPA
        run: |
          flutter build ios --release --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload
          zip -r Runner.ipa Payload
          rm -rf Payload
          ls -l Runner.ipa # Verify IPA creation
      # Upload the IPA as an artifact
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: app-ipa
          path: build/ios/iphoneos/Runner.ipa
Update Podfile · markoviandevelopments/brubaker_home_app@122c37e 
