name: Build iOS IPA
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-ios:
    runs-on: macos-13
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.7'
          channel: 'stable'
          cache: true
      # Install dependencies
      - name: Install dependencies
        run: flutter pub get
      # Build unsigned iOS app and package into unsigned IPA
      - name: Build unsigned IPA
        run: |
          flutter build ios --release --no-codesign
          cd ios
          xcodebuild -workspace Runner.xcworkspace -scheme Runner -sdk iphoneos -configuration Release archive -archivePath ../build/Runner.xcarchive CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
          xcrun xcodebuild -exportArchive -archivePath ../build/Runner.xcarchive -exportOptionsPlist exportOptions.plist -exportPath ../build
          ls -l ../build/Runner.ipa


          
      # Upload the IPA as an artifact
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: app-ipa
          path: build/ios/iphoneos/Runner.ipa
