name: Build iOS IPA
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
      # Add Release configuration if missing
      - name: Add Release configuration
        run: |
          gem install xcodeproj
          ruby -e "
          require 'xcodeproj'
          project = Xcodeproj::Project.open('ios/Runner.xcodeproj')
          project.add_build_configuration('Release', :release)
          project.targets.each do |target|
            target.add_build_configuration('Release', :release)
          end
          project.save
          "
      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.7'
          channel: 'stable'
          cache: true
      # Install dependencies
      - name: Install dependencies
        run: flutter pub get
      # Build unsigned iOS app and package into unsigned IPA
      - name: Build unsigned IPA
        run: |
          flutter build ios --release --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload
          zip -r brubaker_homeapp.ipa Payload
          rm -rf Payload
          ls -l brubaker_homeapp.ipa
      # Upload the IPA as an artifact
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: app-ipa
          path: build/ios/iphoneos/brubaker_homeapp.ipa
