name: Build Unsigned iOS IPA

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Xcode version (use a stable version compatible with your project)
      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.0.app

      # Install dependencies (if using CocoaPods or similar)
      - name: Install dependencies
        run: |
          if [ -f "Podfile" ]; then
            pod install
          fi

      # Build the app and export unsigned IPA
      - name: Build and export unsigned IPA
        run: |
          chmod +x ./scripts/export-unsigned-ipa.sh
          ./scripts/export-unsigned-ipa.sh
        env:
          SCHEME_NAME: "BrubakerHomeApp"  # Replace with your Xcode scheme name
          PROJECT_NAME: "BrubakerHomeApp"  # Replace with your .xcodeproj name
          ARCHIVE_PATH: "./build/BrubakerHomeApp.xcarchive"
          EXPORT_PATH: "./build/unsigned"

      # Upload the IPA as an artifact
      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-ipa
          path: ./build/unsigned/BrubakerHomeApp.ipa
