name: Build iOS IPA

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-14

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.7' # Matches your local Flutter version
          channel: 'stable'
          cache: true

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Build iOS app without signing
      - name: Build iOS IPA
        run: |
          flutter build ios --release --no-codesign
          cd ios
          xcodebuild -workspace Runner.xcworkspace \
                     -scheme Runner \
                     -sdk iphoneos \
                     -configuration Release \
                     -archivePath build/Runner.xcarchive \
                     archive \
                     CODE_SIGNING_ALLOWED=NO
          xcodebuild -exportArchive \
                     -archivePath build/Runner.xcarchive \
                     -exportOptionsPlist exportOptions.plist \
                     -exportPath build \
                     CODE_SIGNING_ALLOWED=NO

      # Create exportOptions.plist for unsigned IPA
      - name: Create exportOptions.plist
        run: |
          cat << EOF > ios/exportOptions.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>development</string>
            <key>signingStyle</key>
            <string>manual</string>
            <key>compileBitcode</key>
            <false/>
            <key>teamID</key>
            <string></string>
          </dict>
          </plist>
          EOF

      # Upload the IPA as an artifact
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: app-ipa
          path: ios/build/Runner.ipa