name: Build Signed iOS IPA

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.1'
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Decode certificate
      run: |
        echo "${{ secrets.IOS_CERTIFICATE_APPSTORE }}" | base64 --decode > appstore.p12 || { echo "Certificate decode failed"; exit 1; }
        ls -l appstore.p12  # Diagnostic: Check file size (should be ~3KB or more)
        file appstore.p12  # Diagnostic: Check file type (should be PKCS#12)

    - name: Decode provisioning profile
      run: |
        echo "${{ secrets.PROVISIONING_PROFILE_APPSTORE }}" | base64 --decode > appstore.mobileprovision || { echo "Profile decode failed"; exit 1; }
        ls -l appstore.mobileprovision  # Diagnostic: Check file size
        security cms -D -i appstore.mobileprovision | grep UUID  # Diagnostic: Verify UUID

    - name: Setup keychain
      run: |
        security create-keychain -p pwd build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p pwd build.keychain

    - name: Import certificate
      run: |
        security import appstore.p12 -k build.keychain -P "${{ secrets.P12_PASSWORD }}" -T /usr/bin/codesign || { echo "Certificate import failed - verify password and file integrity"; exit 1; }
        security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k pwd build.keychain
        security find-identity -v -p codesigning  # Diagnostic: List identities (should show your certificate)

    - name: Build IPA
      run: flutter build ipa --release --export-method app-store --bundle-version 1.0.0 --bundle-short-version-string 1.0 --provisioning-profile-uuid 0b68e1cd-eff0-4306-a2c4-878008e53bcb

    - name: Archive artifact
      uses: actions/upload-artifact@v4
      with:
        name: brubaker-home-app-ipa
        path: build/ios/ipa/*.ipa
