name: iOS IPA Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.x'  # Use your Flutter version

    - name: Install dependencies
      run: flutter pub get

    - name: Build iOS app without signing
      run: flutter build ios --release --no-codesign

    - name: Create IPA
      run: |
        cd build/ios/iphoneos
        mkdir Payload
        mv Runner.app Payload/
        zip -r app.ipa Payload

    - name: Upload IPA artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-ipa
        path: build/ios/iphoneos/app.ipa

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0.${{ github.run_number }}
        release_name: Release v1.0.${{ github.run_number }}
        draft: false
        prerelease: false

    - name: Upload IPA to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/ios/iphoneos/app.ipa
        asset_name: app.ipa
        asset_content_type: application/octet-stream
